#!/bin/bash

WRF_DIR=${SKRIPS_DIR}/WRFV412_AO/
ln -sf ../caseInput/* .

cp $WRF_DIR/main/wrf.exe .
cp ../runCase.init/wrfbdy_d01 . 
cp ../runCase.init/wrfinput_d01 .
cp ../runCase.init/wrflowinp_d01 .
matlab -nodisplay < updateLowinp.m

cp namelist.input.set namelist.input
mpirun -np 4 wrf.exe
matlab -nodisplay < updateHFlux.m

cp namelist.input.run namelist.input
cp ../coupledCode/esmf_application .
echo "running coupled MITgcm--WRF simulation.."
mpirun -np 4 esmf_application &> log.esmf 
