#!/bin/bash

WRF_DIR=/home/x_sunr/scripps_kaust_model_github/WRFV412_AO_01/

cp ${WRF_DIR}/main/wrf.exe .
cp ../coupledCode/esmf_application .
cp ../runCase.init/wrf*d01 . 
ln -sf ../caseInput/* .

sbatch ./Allsubmit.sh

