#!/bin/bash

echo "cleaning the current folder"
./Allclean

echo "copying the NUOPC--WRF code..."
cp ../coupledSolver/esmf_application .
cp ../coupledSolver/namelist.rc .

echo "running the NUOPC--WRF code..."
mpirun -np 5 esmf_application &> log
