#!/bin/bash

WRF_DIR=${SKRIPS_DIR}/WRFV412_AO/
cp ${WRF_DIR}/main/wrf.exe .
cp ../runCase/*.TBL .
cp ../runCase/CAM* .
cp ../runCase/RRTM* .
cp ../runCase/wrf*d01 .
cp ../runCase/ozone* .

./genSSTin.sh
matlab -nodisplay < updateFlux.m

mpirun -np 16 wrf.exe
