#!/bin/bash

WRF_DIR=/home/rus043/scripps_coupled_model_github/coupler/L3.C2.coupled_CA2018_ring/../../WRFV412_AO_01/
cp ${WRF_DIR}/main/wrf.exe .
cp ../runCase/*.TBL .
cp ../runCase/CAM* .
cp ../runCase/RRTM* .
cp ../runCase/wrf*d01 .
cp ../runCase/ozone* .

./genSSTin.sh
matlab -nodisplay < updateFlux.m

mpirun -np 8 wrf.exe
