#!/bin/bash

WRF_DIR=${SKRIPS_DIR}/WRFV413_AO/

git clone https://github.com/iurnus/scripps_kaust_large_files.git large_files
unzip 'large_files/L3C2_case/*.zip'

ln -sf ../caseInput/* .
cp ${WRF_DIR}/main/real.exe .
cp ${WRF_DIR}/main/wrf.exe .

sbatch ./Allsubmit.sh
