#!/bin/bash

rm -rf *.data
rm -rf *.meta
rm -rf wrfout*
rm -rf tmp*.nc
rm -rf rsl*
rm -rf PET*
rm -rf STD*
rm -rf log.*
rm -rf *.exe
rm -rf namelist.out*
rm -rf *.TBL
rm -rf RRTM*
rm -rf wrf*d01
rm -rf CAM*
rm -rf cplFlux
rm -rf ozone*
rm -rf job*
rm -rf core
