#!/bin/bash

WRF_DIR=/home/x_sunr/scripps_kaust_model_github/WRFV412_AO_01/

cp ${WRF_DIR}/main/wrf.exe .
cp ../runCase/*.TBL .
cp ../runCase/CAM* .
cp ../runCase/RRTM* .
cp ../runCase/wrf*d01 .
cp ../runCase/ozone* .

./genSSTin.sh
./updateFlux.py

sbatch ./Allsubmit.sh
