#!/bin/bash

WRF_DIR=${SKRIPS_DIR}/WRFV413_AO/

cp ${WRF_DIR}/main/wrf.exe .
cp ../runCase/*.TBL .
cp ../runCase/CAM* .
cp ../runCase/RRTM* .
cp ../runCase/wrf*d01 .
cp ../runCase/ozone* .

./genSSTin.sh
~/anaconda3/bin/python updateFlux.py

# sbatch ./Allsubmit.sh
