#!/bin/bash

# Build options for PGI compiler with openmpi on ring 
#
CPP='/usr/bin/cpp -P -traditional -mcmodel=medium'
if test "x$MPI" = xtrue ; then
  CC=${CC:=mpicc}
  FC=${FC:=mpif77}
  F90C=${F90C:=mpif90}
#   CC=${CC:=mpic++}
#   FC=${FC:=mpifort}
#   F90C=${F90C:=mpifort}
else
  CC=pgcc
  FC=pgf77
  F90C=pgf90
fi

# Requires gfortran from 2006 onwards for -fconvert=big-endian
FFLAGS="$FFLAGS -byteswapio -r8 -Mnodclchk -Mextend -mcmodel=medium"

#DEFINES
#
#MPI='true'
#DEFINES='-DWORDLENGTH=4 -DNML_TERMINATOR'
DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DWORDLENGTH=4 -DNML_TERMINATOR'
INCLUDES="-I/$SKRIPS_MPI_DIR/include/ $SKRIPS_NETCDF_INCLUDE"
LIBS="-L/$SKRIPS_MPI_DIR/lib/ $SKRIPS_NETCDF_LIB"

if test "x$IEEE" = x ; then
#  No need for IEEE-754
	FOPTIM=''
#        FOPTIM='-g '
    	FFLAGS="$FFLAGS"
  else
#  Try to follow IEEE-754
# Try to follow IEEE-754
# these may also be useful, but require specific gfortran versions:
# -Wnonstd-intrinsics for gfortran <= 4.3
# -Wintrinsics-std for gfortran >= 4.4
# -Wno-tabs for gfortran >= 4.3
    FFLAGS="$FFLAGS"
# to get plenty of warnings :
# FFLAGS="$FFLAGS -Wconversion -Wimplicit-interface -Wunused-labels"
    FOPTIM='-O0'
# for automatic testing with testreport (but no relation with IEEE arithmetic):
    FOPTIM="$FOPTIM -g "
fi

F90FLAGS=$FFLAGS
F90OPTIM=$FOPTIM
CFLAGS='-O0 -mcmodel=medium'
