#!/bin/bash

WRF_DIR=/home/rus043/scripps_coupled_model_github/coupler/L3.C1.coupled_RS2012_ring/../../WRFV412_AO_01/
cp $WRF_DIR/main/wrf.exe .
cp ../runCase/*.TBL .
cp ../runCase/CAM* .
cp ../runCase/RRTM* .
cp ../runCase/ozone* .
cp ../runCase/wrf*d01 .

./genSSTin.sh
matlab -nodisplay < updateFlux.m

mpirun -np 4 wrf.exe

./genSSTin2.sh
