MITgcm-WRF coupled simulation test: California Current

This folder contains an MITgcm-WRF coupled test case. The coupled simulation is
driven by ESMF. The case aims to test the implementation of the coupled code.
In this test, the ESMF driver drives both MITgcm and WRF. Both MITgcm and WRF
are divided into "init", "run", "finalize" parts. This coupled code drives the
realistic simulations in the California Current region.

The WRF bulf formula is used in this case.
This should be compiled using Intel compiler (run it on shaheen).

simulation:
  California Current region

Notes:
To install and run this case::

./install.sh
cd run
./Allrun

To clean this case::

./clean.sh

How to check if the code is installed?

MITGCM executable is: build/mitgcmuv
MITGCM library is: build/mmout/libmitgcm_org_ocn.a
MITGCM run time library is: build/mmout/libmitgcmrtl.a
MITGCM mod file is: build/mitgcm_org_ocn.mod
The coupled MITGCM-ESMF solver is: coupledCode/esmf_application

####################
WARNING!!!WARNING!!!
####################
The MITgcm path is defined as '/home/x_sunr/scripps_kaust_model_github/MITgcm_c67m' in install.sh
The MPI_HOME path is defined as '/opt/openmpi/intel/ib/include/' in install.sh

The ESMF should be installed to run this case. The variable ESMFMKFILE should
be defined:

  export ESMFMKFILE=$ESMF_DIR/lib/libg/Unicos.intel.64.mpi.default/esmf.mk

where ESMF_DIR should be the location that ESMF is installed.

Make sure Python (Anaconda version) is installed.
Make sure NCL is installed.
Make sure L3C1 case is located at "../L3.C1.coupled_RS2012_ring/"
