#!/bin/bash

WRF_DIR=${SKRIPS_DIR}/WRFV413_AO/

# export CPL_FOLDER='/project/rus043_data/ar_2018_forecast/'
# ln -s ${CPL_FOLDER}/save_nc/fine_loop_3911/2018_0127/met_em.d01.2018-01-2[6-9]*.nc .
# ln -s ${CPL_FOLDER}/save_nc/fine_loop_3911/2018_0127/met_em.d01.2018-01-3[0-9]*.nc .
# ln -s ${CPL_FOLDER}/save_nc/fine_loop_3911/2018_0127/met_em.d01.2018-02-0[1-2]*.nc .

git clone https://github.com/iurnus/scripps_kaust_large_files.git large_files
unzip 'large_files/L3C2_case/*.zip'

cp ../caseInput/* .
cp ${WRF_DIR}/main/real.exe .
cp ${WRF_DIR}/main/wrf.exe .
cp namelist.input.ca.2018.WRF_medium_set namelist.input

echo "running real..."
mpirun -np 8 real.exe &> log.real

matlab -nodisplay < updateLowinp.m

cp namelist.input.ca.2018.WRF_medium_ini namelist.input
echo "setting initial condition..."
mpirun -np 4 wrf.exe &> log.real

matlab -nodisplay < updateHFlux.m

