#!/bin/bash

WRF_DIR=/home/rus043/scripps_kaust_model_github/coupler/L3.C1.coupled_RS2012_ring/../../WRFV412_AO_01/

ln -sf ../save_nc/* .
ln -sf ../caseInput/* .
cp $WRF_DIR/main/real.exe .
cp $WRF_DIR/main/wrf.exe .

mpirun -np 4 real.exe
