#!/bin/bash

# cp /home/rus043/kaust_project/codeNew/regionalCOAM/coupler/coupler_redsea_verification/save_nc/2012_medium/met_em.d01.2012-06-0[1-2]*.nc .
# cp ../../../WPS_RedSea/met_em*nc .

ln -sf ../save_nc/* .
ln -sf ../caseInput/* .
cp ../../../WRFV412_AO/main/real.exe .
cp ../../../WRFV412_AO/main/wrf.exe .

mpirun -np 4 real.exe
