#!/bin/bash

CC='cc'
FC='ftn'
F90C='ftn'

DEFINES='-DWORDLENGTH=4 -DALLOW_USE_MPI -DALWAYS_USE_MPI -DHAVE_SETRLSTK -DHAVE_SIGREG -DHAVE_STAT -DHAVE_FLUSH'
CPP='cpp -traditional -P -mcmodel=medium'
EXTENDED_SRC_FLAG='-Mextend'
GET_FC_VERSION="-V"
CHECK_FOR_LAPACK=t

INCLUDES='-I/opt/cray/pe/netcdf/4.4.1.1.6/INTEL/16.0/include -I/opt/cray/pe/parallel-netcdf/1.8.1.3/INTEL/16.0/include -I/opt/cray/pe/mpt/7.7.0/gni/mpich-intel/16.0/include'
LIBS='-L/opt/cray/pe/netcdf/4.4.1.1.6/INTEL/16.0/lib -L/opt/cray/pe/parallel-netcdf/1.8.1.3/INTEL/16.0/lib -L/opt/cray/pe/mpt/7.7.0/gni/mpich-intel/16.0/lib'

NOOPTFLAGS='-O2'
NOOPTFILES=''

if test "x$IEEE" = x ; then   #- with optimisation:
#   FOPTIM='-O2 -hfp3 -Oipa5' for less agressive optimization 
#   Be aware not all experiments pass the restart test with optimization 
    FOPTIM='-g -convert big_endian -assume byterecl'
    # '-w95 -g -convert big_endian -assume byterecl'
else
    if test "x$DEVEL" = x ; then  #- no optimisation + IEEE :
      FOPTIM='-O2'
    else                          #- development/check options:
      FOPTIM='-O2'
      FOPTIM="$FOPTIM -g"
    fi
fi

