#!/bin/bash

CC='cc'
FC='ftn'
F90C='ftn'

DEFINES='-DWORDLENGTH=4 -DALLOW_USE_MPI -DALWAYS_USE_MPI -DHAVE_SETRLSTK -DHAVE_SIGREG -DHAVE_STAT -DHAVE_FLUSH'
CPP='cpp -traditional -P -mcmodel=medium'
EXTENDED_SRC_FLAG='-Mextend'
GET_FC_VERSION="-V"
CHECK_FOR_LAPACK=t

INCLUDES="-I/$MPI_INC -I$SKRIPS_NETCDF_INCLUDE"
LIBS="-L/$MPI_LIB -I$SKRIPS_NETCDF_LIB"

NOOPTFLAGS='-O2'
NOOPTFILES=''

if test "x$IEEE" = x ; then   #- with optimisation:
#   FOPTIM='-O2 -hfp3 -Oipa5' for less agressive optimization 
#   Be aware not all experiments pass the restart test with optimization 
    FOPTIM='-g -convert big_endian -assume byterecl'
    # '-w95 -g -convert big_endian -assume byterecl'
else
    if test "x$DEVEL" = x ; then  #- no optimisation + IEEE :
      FOPTIM='-O2'
    else                          #- development/check options:
      FOPTIM='-O2'
      FOPTIM="$FOPTIM -g"
    fi
fi

